version: "3"

services:
  web:
    build: .
    env_file:
      - ../../.env
    command: bash -c "python manage.py runsslserver 0.0.0.0:443"
    volumes:
      - ../../django_tequila:/usr/local/lib/python3.6/site-packages/django_tequila
      - .:/usr/src
    ports:
      - "443:443"
      # this port is for debug tools
      - "4445:4445"
